name: Build

on:
  # release:
  #   types: [published]
  create:
    tags:        
      - '**'
  push:
   branches:
    - 'main'
   paths:
    - '.gitea/workflows/Build.yaml'

jobs:
  registry-build:
    env: 
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    runs-on: bookworm
    steps:
      - name: Install Docker
        run: |
          apt-get update -qq >/dev/null
          DEBIAN_FRONTEND=noninteractive apt-get install -y -qq gpg apt-transport-https ca-certificates curl >/dev/null
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
          apt-get update -qq >/dev/null
          DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
          docker info

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Zip (URL)
        if: ${{ ! gitea.ref_name }}
        run: |
          wget -c ${{vars.INSTALL_URL}} -O ./build.zip
          unzip -o ./build.zip
          rm ./build.zip
      
      - name: Get Zip (Tag)
        if: ${{  gitea.ref_name }}
        run: |
          wget -c ${{vars.INSTALL_URL}} -O ./build.zip
          unzip -o ./build.zip
          rm ./build.zip

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{vars.REGISTRY_URL}}"] 
              http = true
              insecure = true 

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{vars.REGISTRY_URL}}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.REGISTRY_PASS  }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{vars.REGISTRY_URL}}/${{ gitea.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push to Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ gitea.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ gitea.repository }}:latest
      
      - name: Inspect Image
        run: |
          docker image ls
          docker buildx imagetools inspect ${{vars.REGISTRY_URL}}/${{ gitea.repository }}:latest

      - name: Export image to tar.gz
        run: |
          docker image save -o latest.tar ${{vars.REGISTRY_URL}}/${{ gitea.repository }}:latest
          gzip latest.tar
      
      - name: Create Release
        uses: akkuman/gitea-release-action@v1
        with:
          server_url: http://${{vars.REGISTRY_URL}}
          name: ${{ gitea.ref_name }}
          tag_name: ${{ gitea.ref_name }}
          draft: ""
          prerelease: ""
          files: ./latest.tar.gz