name: ServiceNow Mid Server Docker Build

on:
  workflow_dispatch:
  #schedule:
    #- cron: '00 22 1 1/3 *'
  push:
    branches:
      - 'main'
    tags:
      - '*'
  #pull_request:
    #branches:
      #- 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            gitea.kanis.dev/${{ gitea.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      # - name: Set up QEMU
        # uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Inspect
        run: |
          docker buildx imagetools inspect gitea.kanis.dev/${{ gitea.repository }}:latest  