name: Docker Build

on:
  create:
    tags:        
      - '**'

jobs:
  docker-build:
    uses: bkanis/apt-cacher-ng/.gitea/workflows/Docker_Build.yaml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_CALLER }}

  # registry-build:
  #   env: 
  #     RUNNER_TOOL_CACHE: /toolcache
  #   runs-on: ${{vars.BUILD_IMAGE}}
  #   steps:
  #     - name: Setup Environment
  #       run: |
  #         apt-get update -qq >/dev/null
  #         DEBIAN_FRONTEND=noninteractive apt-get install -y -qq gpg apt-transport-https ca-certificates curl unzip gzip >/dev/null
  #         install -m 0755 -d /etc/apt/keyrings
  #         curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
  #         chmod a+r /etc/apt/keyrings/docker.gpg
  #         echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
  #         apt-get update -qq >/dev/null
  #         DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
  #         docker info

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
     
  #     - name: Get Zip
  #       run: |
  #         curl -o ./${{ gitea.ref_name }}.Docker.zip "${{vars.INSTALL_URL}}"
  #         unzip -o ./${{ gitea.ref_name }}.Docker.zip 

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         config-inline: |
  #           [registry."${{vars.REGISTRY_URL}}"] 
  #             http = true
  #             insecure = true 

  #     - name: Login to Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{vars.REGISTRY_URL}}
  #         username: ${{ gitea.repository_owner }}
  #         password: ${{ secrets.REGISTRY_PASS  }}

  #     - name: Set Image Metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: |
  #           ${{vars.REGISTRY_URL}}/${{ gitea.repository }}
  #         tags: |
  #           # SHA
  #           type=sha
  #           # Latest (On default branch)
  #           type=raw,value=latest,enable={{is_default_branch}}
  #           # Tag from Tag
  #           type=ref,event=tag

  #     - name: Build and Push Image to Registry
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: ${{ gitea.event_name != 'pull_request' }}
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #         cache-from: type=registry,ref=${{ gitea.repository }}:latest
  #         outputs: type=oci,dest=/tmp/${{ gitea.ref_name }}.tar
      
  #     - name: Verify Image
  #       run: |
  #         docker image ls
  #         docker buildx imagetools inspect ${{vars.REGISTRY_URL}}/${{ gitea.repository }}:latest

  #     # - name: Compress Artifacts # Not much gain with Docker images
  #     #   run: |
  #     #     gzip -9 < /tmp/${{ gitea.ref_name }}.tar > /tmp/${{ gitea.ref_name }}.tar.gz

  #     - name: Create Release
  #       uses: akkuman/gitea-release-action@v1
  #       with:
  #         server_url: http://${{vars.REGISTRY_URL}}
  #         name: ${{ gitea.ref_name }}
  #         tag_name: ${{ gitea.ref_name }}
  #         draft: ""
  #         prerelease: ""
  #         files: |
  #           ./${{ gitea.ref_name }}.Docker.zip
  #           /tmp/${{ gitea.ref_name }}.tar